Update 02-domain

diff --git a/02-domain b/02-domain
--- a/02-domain
+++ b/02-domain
@@ -257,9 +257,13 @@ sleep 0.5
 
 echo ""; echo "############################################################"
 echo ""; echo "Checking if container is Ok, UP and Running:"; echo ""
-echo "5"; sleep 1; echo "4"; sleep 1; echo "3"; sleep 1; echo "2"; sleep 1; echo "1"; sleep 1; echo "0"; sleep 1
-echo ""; echo "Active Directory & Domain Controller is Ok, UP and Running!"; echo ""
-sleep 3
+cont1=$(docker inspect $NOMECONTAINER | grep running | awk {'print $2'} | cut -c 2,3,4,5,6,7,8)
+  [ "$cont1" = "running" ] && {
+    echo "Active Directory & Domain Controller is Ok, UP and Running!"; echo ""
+  } || {
+    echo "SOME ERROR OCCURRED. CHECK THE DOMAIN CONTAINER!"; echo ""
+  }
+sleep 0.5
 
 unset var1
 unset var2
