Update 31-unifi-network

diff --git a/31-unifi-network b/31-unifi-network
--- a/31-unifi-network
+++ b/31-unifi-network
@@ -5,12 +5,25 @@ NOMECONTAINER="unifi-network"
 docker_repo="lscr.io/linuxserver/unifi-network-application:latest"
 imagem="unifi"
 
-randompass=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 8; echo)
+DB_PASS=$(yq ".\"${mongodb}\".db_pass" "/srv/containers.yaml")
+if [ "$DB_PASS" != "null" ] && [ -n "$DB_PASS" ]; then
+    clear; echo "Dados encontrados!"; sleep 1
+else
+    clear
+    echo "ERROR: CRIE OU RECRIE O BANCO DE DADOS MONGODB PRIMEIRO!"
+    echo "Saindo..."
+    echo ""
+    sleep 5
+    exit 1
+fi
+
+DB_NAME=$(yq ".\"${mongodb}\".db_name" "/srv/containers.yaml")
+DB_IP=$(yq ".\"${mongodb}\".local_ip" "/srv/containers.yaml")
 
 CustmN2="local_ip"
 CustmN3="servidor_dns"
-CustmN4=""
-CustmN5=""
+CustmN4="db_name"
+CustmN5="db_pass"
 CustmN6=""
 CustmN7=""
 CustmN8=""
@@ -19,8 +32,8 @@ CustmN10=""
 
 VALUE2="0.0.0.0"
 VALUE3="8.8.4.4"
-VALUE4=""
-VALUE5=""
+VALUE4="$DB_NAME"
+VALUE5="$DB_PASS"
 VALUE6=""
 VALUE7=""
 VALUE8=""
@@ -41,8 +54,14 @@ function docker_create {
     --network host \
     --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
     -e PUID=1000 -e PGID=1000 \
-    -e MEM_LIMIT=1024 -e MEM_STARTUP=1024 \
-    -e MONGO_USER=unifi -e MONGO_PASS="$VALUE6" -e MONGO_HOST="$VALUE5" -e MONGO_PORT=27017 -e MONGO_DBNAME=unifi -e MONGO_AUTHSOURCE=admin -e MONGO_TLS= \
+    -e MEM_LIMIT=2048 -e MEM_STARTUP=1024 \
+    -e MONGO_USER=unifi \
+    -e MONGO_PASS="$VALUE5" \
+    -e MONGO_HOST="$DB_IP" \
+    -e MONGO_PORT=27017 \
+    -e MONGO_DBNAME=unifi \
+    -e MONGO_AUTHSOURCE=admin \
+    -e MONGO_TLS= \
     -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -p 8080:8080 -p 1900:1900/udp -p 8843:8843 -p 8880:8880 -p 6789:6789 -p 5514:5514/udp \
     -v /srv/containers/"$NOMECONTAINER"/config:/config \
     "$docker_repo"
@@ -55,7 +74,13 @@ function docker_create {
   --no-healthcheck --restart=unless-stopped -v /etc/localtime:/etc/localtime:ro \
   -e PUID=1000 -e PGID=1000 \
   -e MEM_LIMIT=1024 -e MEM_STARTUP=1024 \
-  -e MONGO_USER=unifi -e MONGO_PASS="$VALUE6" -e MONGO_HOST="$VALUE5" -e MONGO_PORT=27017 -e MONGO_DBNAME=unifi -e MONGO_AUTHSOURCE=admin -e MONGO_TLS= \
+  -e MONGO_USER=unifi \
+  -e MONGO_PASS="$VALUE5" \
+  -e MONGO_HOST="$DB_IP" \
+  -e MONGO_PORT=27017 \
+  -e MONGO_DBNAME=unifi \
+  -e MONGO_AUTHSOURCE=admin \
+  -e MONGO_TLS= \
   -v /srv/containers/"$NOMECONTAINER"/config:/config \
   "$docker_repo"
 }
