Update ClusterHA

diff --git a/ClusterHA b/ClusterHA
--- a/ClusterHA
+++ b/ClusterHA
@@ -1,131 +1,132 @@
 #!/bin/bash
 
-# SUDO Cron: "@reboot sleep 15; bash /home/ubuntu/Script/Cluster"
-
-# Explanation:
-# 00 - Check if GLusterFS service is Running
-# 01 - Check if the Volume /srv/containers is mounted
-# 02- Ping if there is ethernet connection on DHCP Server.
-# If no ping, do not run anything!
-# If ping DHCP...
-# 03 - Ping the other node.
-# If no ping, start all Containers.
-# If ping node...
-# 04 - Check PIDFile on other node.
-# If PIDFile is 0, start all containers.
-# If PIDFile is 1, stop all containers.
-
 function init {
 # ============================================================================ #
 
+# SUDO Cron: "@reboot sleep 15; bash /home/ubuntu/Script/Cluster"
+
 # Control Panel #
 
-IP1="172.20.0.50" # Primary Node
-IP2="172.20.0.51" # Secondary Node
+IP1="172.20.0.10" # Primary Node
+HOSTNAME1="cluster-01"
 
-IP3="172.20.0.1" # Local DHCP Server
+IP2="172.20.0.11" # Secondary Node
+HOSTNAME2="cluster-02"
 
-mntpath="/mnt/cluster01"
+IP3="172.20.0.1" # Local Gateway Server
+
+volumepath="/mnt/volume01"
 
 lognull="/dev/null"
-logpath="/var/log/cluster"
-
-# If Primary... Uncomment!
-#clusterP0
+logpath="/var/log/gluster"
 
 # ============================================================================ #
+
+touch $logpath
+
 while true; do
-  data=$(date +"%Y_%m_%d_%H:%M")
-  sleep 1;
-  cluster00
+  data=$(date +".%H.%M.:.%d.%m.%Y.")
+  sleep 5;
+  gluster00
 done
+}
+
+# 00 - Check if GlusterFS service is Running
+function gluster00 {
+  systemctl is-active --quiet glusterd && {
+    gluster01
+  } || {
+    echo "$data Glusterd.service not found. Trying start..." >> $logpath
+    systemctl start glusterd.service
+    systemctl is-active --quiet glusterd && {
+    echo "$data Glusterd started!" >> $logpath
+      gluster01
+    } || {
+      echo "$data ERROR: Glusterd not running!" >> $logpath
+      # Higher Beep
+      modprobe pcspkr
+      env -u SUDO_GID -u SUDO_COMMAND -u SUDO_USER -u SUDO_UID beep -f 2000 -l 200 -r 1
+      env -u SUDO_GID -u SUDO_COMMAND -u SUDO_USER -u SUDO_UID beep -f 2000 -l 200 -r 1
+    }
+  }
+}
+
+# 01 - Check if the Volume in /srv/containers is mounted
+function gluster01 {
+  # Gluster is the only one that creates localhost lines on mtab
+  cat /etc/mtab | grep localhost 1>$lognull 2>$lognull && {
+    cluster00
+  } || {
+    echo "$data Volume not found. Trying mount..." >> $logpath
+    mount -a
+    cat /etc/mtab | grep volume 1>$lognull 2>$lognull && {
+      echo "$data Volume mounted!" >> $logpath
+      cluster00
+    } || {
+      echo "$data ERROR: Volume not found!" >> $logpath
+      # Lower Beep
+      modprobe pcspkr
+      env -u SUDO_GID -u SUDO_COMMAND -u SUDO_USER -u SUDO_UID beep -f 1000 -l 200 -r 1
+      env -u SUDO_GID -u SUDO_COMMAND -u SUDO_USER -u SUDO_UID beep -f 1000 -l 200 -r 1
+    }
+  }
+}
+
+# 02- Ping if there is connection to Gateway route.
+function cluster00 {
+  if ping -c 1 $IP3 &> $lognull; then
+    echo "." >> $lognull
+    sleep 1;
+    cluster01
+  else
+    echo "$data ERROR: Gateway not found" >> $logpath
+    modprobe pcspkr
+    env -u SUDO_GID -u SUDO_COMMAND -u SUDO_USER -u SUDO_UID beep -f 2000 -l 200 -r 1
+    env -u SUDO_GID -u SUDO_COMMAND -u SUDO_USER -u SUDO_UID beep -f 1000 -l 200 -r 1
+  fi
+}
+
+# 03 - Ping the other node.
+function cluster01 {
+  if ping -c 1 $IP1 &> $lognull && ping -c 1 $IP2 &> $lognull; then
+    cluster02
+  else
+    echo "$data ERROR: The other node does not ping. Starting as MASTER." >> $logpath
+    dockerctrl start &&
+    setpid "1"
+  fi
+}
+
+# 04 - Checking for PIDFile on the other node.
+function cluster02 {
+  [ "$HOSTNAME" = "$HOSTNAME1" ] &&
+    checking=$(ssh $HOSTNAME2 "cat ~/.lockha")
+    lockha
+  } || {
+    checking=$(ssh $HOSTNAME1 "cat ~/.lockha")
+    lockha
+  }
+}
+
+function lockha {
+  [ "$checking" = "1" ] && {
+      dockerctrl stop &&
+      echo "0" | tee ~/.lockha
+    } || {
+      dockerctrl start &&
+      echo "1" | tee ~/.lockha
+    }
 }
 
 function dockerctrl {
   docker "$1" $(docker ps -a -q)
 }
-dockerctrl stop &&
 
-
-# Function just for Primary!
-
-# Var
-control="0" # Default at boot
-
-function clusterP0 {
-  if [ $control = "1" ]; then # if 1:
-    echo "Nothing more to do here." >> $lognull
-  else # elif 0...
-    control="1" # Only once in time, at boot!
-    echo "First run." >> $logpath
-    cluster03
-    sleep 1;
-  fi
+function setpid {
+  touch ~/.lockha
+  echo "$1" | tee ~/.lockha
 }
-
-# Functions to Both Servers!
-
-# 00 - Local Ping
-function cluster00 {
-  if ping -c 1 $IP3 &> $lognull; then # Se pingou!
-    echo "Nothing more to do here." >> $lognull
-    sleep 1;
-    cluster01
-  else # Não pingou!
-    echo "$data ERROR 01: Local ping. Canceling check." >> $logpath
-  fi
-}
-
-# 01 - Cluster Ping
-function cluster01 {
-  if ping -c 1 $IP1 &> $lognull && ping -c 1 $IP2 &> $lognull; then
-    echo "Nothing more to do here." >> $lognull
-  else
-    echo "$data ERROR 02: Cluster ping. Starting check." >> $logpath
-    sleep 1;
-    cluster02
-  fi
-}
-
-# 02 - Mount Check
-function cluster02 { # Se Montado!
-  if grep -qs $mntpath /proc/mounts; then
-    echo "Nothing more to do here." >> $lognull
-  else # Não montado
-    echo "$data ERROR 03: Path not Mounted" >> $logpath
-    sleep 1;
-    cluster03
-  fi
-}
-
-# 03 - Sequência de Estabilização
- 
-function cluster03 {
-  if drbdadm primary --force all; then
-    echo "Nothing more to do here." >> $lognull
-  else
-    echo "$data ERROR 04: DRBD" >> $lognull
-  fi
-  sleep 10;
-
-  if mount $mntpath1; then
-    echo "Nothing more to do here." >> $lognull
-  else
-    echo "$data ERROR 06: Cant Mount 01" >> $logpath
-  fi
-  sleep 5;
-  
-  if systemctl restart smbd nmbd; then
-    echo "Nothing more to do here." >> $lognull
-  else 
-    echo "$data ERROR 08: SMBd & NMBd" >> $logpath
-  fi
-  sleep 1;
-  
-  # Try Initialize all VMs
-  for i in $(virsh list --name); do virsh start $i; done
-}
-
-# Start #
 
 init
+
+exit 1
