Update ClusterHA

diff --git a/ClusterHA b/ClusterHA
--- a/ClusterHA
+++ b/ClusterHA
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# notSUDO Cron: "@reboot sleep 15; bash /path/out/drbd/Cluster"
+# notSUDO Cron: "@reboot sleep 15; bash /caminho/FORA/do/drbd/Cluster"
 # enabled systemd-networkd-wait-online.service
 
 function init {
@@ -16,6 +16,7 @@ IP2="170.11.1.3"
 lognull="/dev/null"
 logpath="/var/log/cluster"
 
+rm /var/log/cluster
 touch /var/log/cluster
 
 while true; do
@@ -26,27 +27,31 @@ done
 }
 
 function cluster00 {
-  # Check if folder ir mounted under DRBD
+# Check if localhost and node02 are pinging
+result1=$(ping -c 1 $IP1 &> /dev/null && echo sim || echo nao)
+result2=$(ping -c 1 $IP2 &> /dev/null && echo sim || echo nao)
+[ $result1 = "sim" ] && [ $result2 = "sim" ] && {
+  # If both ping = Ok
+  echo "Nothing to do here." >> $lognull
+} || {
+  # Does not ping, so check if folder is mounted under DRBD
   [ -d /mnt/cluster01/Containers ] && {
-    # Check if localhost and node02 are pinging
-    result1=$(ping -c 1 $IP1 &> /dev/null && echo sim || echo nao)
-    result2=$(ping -c 1 $IP2 &> /dev/null && echo sim || echo nao)
-    
-    # If both ping = Ok
-    [ $result1 = "sim" ] && [ $result2 = "sim" ] && {
-      echo "Nothing to do here." >> $lognull
-    } || {
-      # Mounted but not ping = Start
-      echo "$data ERROR 01: Cluster does not ping." >> $logpath
-      for i in $(docker container ls --format 'table {{.Names}}' | tail -n +2); do docker start $i; echo "$data started $i" >> $logpath; done
-      }
-    }
-
+    echo "$data ERROR 01: Cluster does not ping, starting all containers." >> $logpath
+    for i in $(docker ps -a -q)
+    do
+      docker start $i
+      echo "$data started $i" >> $logpath
+    done
   } || {
-    # Not mounted but ping = Stop
-    echo "$data ERROR 02: Main folder is not found! Stopping all containers." >> $logpath
-    for i in $(docker container ls --format 'table {{.Names}}' | tail -n +2); do docker stop $i; echo "$data stopped $i" >> $logpath; done
+    echo "$data ERROR 02: Mount point not found, stopping all containers." >> $logpath
+    for i in $(docker ps -a -q)
+    do
+      docker stop $i
+      echo "$data stopped $i" >> $logpath
+    done
     }
+  }
+}
 
 # Start #
 init
